apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.5.0
    helm:
      valuesObject:
        global:
          repository: "internal.harbor.no/ghcrcache/external-secrets/external-secrets"
        bitwarden-sdk-server:
          enabled: true
          image:
            repository: "internal.harbor.no/ghcrcache/external-secrets/bitwarden-sdk-server"
            tls:
              enabled: true
              # Name of the secret that contains the TLS cert. Ignored when `image.tls.volumes` is set
              # secretName: bitwarden-tls-certs
              # Use this to override the default volumes
              volumes:
                - name: bitwarden-tls-certs
                  secret:
                    secretName: bitwarden-tls-certs
                    items:
                      - key: tls.crt
                        path: cert.pem
                      - key: tls.key
                        path: key.pem
                      - key: ca.crt
                        path: ca.pem
                - name: bitwarden-ca-bundle
                  configMap:
                    name: bitwarden-ca-bundle
                    items:
                      - key: ca-certificates.crt
                        path: ca-certificates.crt
              # Use this to override the default volume mounts
              volumeMounts:
                - mountPath: /certs
                  name: bitwarden-tls-certs
                - mountPath: /etc/ssl/certs/ca-certificates.crt
                  name: bitwarden-ca-bundle
                  subPath: ca-certificates.crt
                  readOnly: true
          serviceAccount:
            create: false
          podSecurityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true # Required! Without this, not all parts of the helm chart will be applied.
    automated:
      prune: false
      selfHeal: true
